let yourAge = 29
let yearOfBirth = 1993
let birthday = 14
let brothers = 2
let sisters = 2
let numberPeopleFamily = 6
let costToStudyInRubles = 28
let thisYear = 2022
let usdExchangeRate = 61.13
let eurExchangeRate = 60.10
let btcExchangeRate = 1213300

let ageResult = thisYear - yearOfBirth
let yearOfBirthResult = thisYear - yourAge
let numberPeopleFamilyResult = brothers + sisters
let amountOfEuro = eurExchangeRate * 1000
let amountOfDollars = usdExchangeRate * 2.5
let amountOfBTC =btcExchangeRate / 10000
let costDividedUSD = costToStudyInRubles / usdExchangeRate
let divideTheFamily = numberPeopleFamily - brothers - sisters
let nullDivideAge =0 / yourAge
let remainderYear35 = 35 - yourAge